-- 1. CREACION DE TABLESPACES
-- Separamos los datos de los indices para mejorar el rendimiento
CREATE TABLESPACE ts_datos DATAFILE 'ts_datos.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE ts_indices DATAFILE 'ts_indices.dbf' SIZE 50M AUTOEXTEND ON;

-- 2. CREACION DE TABLAS (Se usa GENERATED BY DEFAULT AS IDENTITY en lugar de SERIAL de PostgreSQL)

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(30) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    rol VARCHAR2(10) CHECK (rol IN ('ADMIN', 'EMPRESA', 'USUARIO')),
    fecha_registro DATE DEFAULT SYSDATE,
    activo NUMBER(1) DEFAULT 1
) TABLESPACE ts_datos PCTFREE 10 PCTUSED 40;

CREATE TABLE perfil_usuario (
    id_perfil NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    nombre_completo VARCHAR2(100),
    avatar BLOB,
    descripcion VARCHAR2(500)
) TABLESPACE ts_datos;

CREATE TABLE empresa_datos (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    nombre_empresa VARCHAR2(100),
    logo BLOB,
    sitio_web VARCHAR2(200),
    verificado NUMBER(1) DEFAULT 0
) TABLESPACE ts_datos;

CREATE TABLE videojuego (
    id_juego NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa NUMBER REFERENCES usuario(id_usuario),
    titulo VARCHAR2(200) NOT NULL,
    descripcion CLOB,
    precio NUMBER(10,2) CHECK (precio >= 0),
    fecha_lanzamiento DATE,
    estado VARCHAR2(2) DEFAULT 'PE' CHECK (estado IN ('PE','AP','RE')),
    portada BLOB,
    trailer BLOB,
    requisitos CLOB,
    fecha_subida DATE DEFAULT SYSDATE,
    fecha_aprobacion DATE,
    aprobado_por NUMBER REFERENCES usuario(id_usuario),
    modo_almacenamiento VARCHAR2(4) DEFAULT 'BLOB' CHECK (modo_almacenamiento IN ('BLOB','RUTA')),
    portada_ruta VARCHAR2(500),
    trailer_ruta VARCHAR2(500)
) TABLESPACE ts_datos PCTFREE 20;

CREATE TABLE genero (
    id_genero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) UNIQUE NOT NULL
) TABLESPACE ts_datos PCTFREE 0;

CREATE TABLE videojuego_genero (
    id_juego NUMBER REFERENCES videojuego(id_juego) ON DELETE CASCADE,
    id_genero NUMBER REFERENCES genero(id_genero) ON DELETE CASCADE,
    PRIMARY KEY (id_juego, id_genero)
) TABLESPACE ts_datos;

CREATE TABLE carrito (
    id_carrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_juego NUMBER REFERENCES videojuego(id_juego) ON DELETE CASCADE,
    fecha_agregado DATE DEFAULT SYSDATE
) TABLESPACE ts_datos;

CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario),
    fecha_pedido DATE DEFAULT SYSDATE,
    total NUMBER(10,2),
    estado VARCHAR2(20) DEFAULT 'COMPLETADO'
) TABLESPACE ts_datos;

CREATE TABLE detalle_pedido (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido NUMBER REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    id_juego NUMBER REFERENCES videojuego(id_juego),
    precio_pagado NUMBER(10,2)
) TABLESPACE ts_datos;

CREATE TABLE biblioteca (
    id_biblioteca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_juego NUMBER REFERENCES videojuego(id_juego) ON DELETE CASCADE,
    fecha_adquisicion DATE DEFAULT SYSDATE,
    UNIQUE(id_usuario, id_juego)
) TABLESPACE ts_datos;

CREATE TABLE auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuario(id_usuario),
    accion VARCHAR2(100),
    descripcion VARCHAR2(500),
    fecha DATE DEFAULT SYSDATE
) TABLESPACE ts_datos PCTFREE 5;

-- 3. PARTICIONAMIENTO POR LISTA (REQUERIMIENTO DEL PROYECTO PARTE 3)
CREATE TABLE calificaciones_part (
    id_calificacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_juego NUMBER REFERENCES videojuego(id_juego) ON DELETE CASCADE,
    puntuacion NUMBER(1) CHECK (puntuacion BETWEEN 1 AND 5),
    comentario CLOB,
    fecha DATE DEFAULT SYSDATE,
    UNIQUE(id_usuario, id_juego)
) TABLESPACE ts_datos PCTFREE 10 PCTUSED 40
PARTITION BY LIST (puntuacion) (
    PARTITION p1 VALUES (1) TABLESPACE ts_datos,
    PARTITION p2 VALUES (2) TABLESPACE ts_datos,
    PARTITION p3 VALUES (3) TABLESPACE ts_datos,
    PARTITION p4 VALUES (4) TABLESPACE ts_datos,
    PARTITION p5 VALUES (5) TABLESPACE ts_datos
);

-- 4. INDICES COMUNES (Asignados al tablespace de indices)
CREATE INDEX idx_usuario_rol ON usuario(rol) TABLESPACE ts_indices;
CREATE INDEX idx_usuario_email ON usuario(email) TABLESPACE ts_indices;
CREATE INDEX idx_videojuego_empresa ON videojuego(id_empresa) TABLESPACE ts_indices;
CREATE INDEX idx_videojuego_titulo ON videojuego(titulo) TABLESPACE ts_indices;
CREATE INDEX idx_pedido_usuario ON pedido(id_usuario) TABLESPACE ts_indices;
CREATE INDEX idx_pedido_fecha ON pedido(fecha_pedido) TABLESPACE ts_indices;
CREATE INDEX idx_biblioteca_usuario ON biblioteca(id_usuario) TABLESPACE ts_indices;
CREATE INDEX idx_calificaciones_juego ON calificaciones_part(id_juego) TABLESPACE ts_indices;

-- 5. INDICE BITMAP (REQUERIMIENTO DEL PROYECTO PARTE 3)
-- Excelente para columnas de baja cardinalidad (PE, AP, RE)
CREATE BITMAP INDEX idx_videojuego_estado_bitmap ON videojuego(estado) TABLESPACE ts_indices;

-- 6. TABLAS HISTÓRICAS Y RESPALDOS LÓGICOS
CREATE TABLE usuario_eliminado (
    id_usuario NUMBER,
    username VARCHAR2(30),
    email VARCHAR2(100),
    rol VARCHAR2(10),
    fecha_registro DATE,
    fecha_eliminacion DATE DEFAULT SYSDATE
) TABLESPACE ts_datos;

-- Respaldo temporal de bibliotecas al revocar un juego
CREATE TABLE biblioteca_revocada (
    id_biblioteca NUMBER,
    id_usuario NUMBER,
    id_juego NUMBER,
    fecha_adquisicion DATE,
    fecha_revocacion DATE DEFAULT SYSDATE
) TABLESPACE ts_datos;

-- 7. DATOS DE PRUEBA INICIALES
-- (Nota: Para este entorno las contrasenas estan en texto plano para facilitar tu acceso con el auth_controller actual)
INSERT INTO usuario (username, email, password_hash, rol) 
VALUES ('admin_root', 'admin@bda.com', 'admin123', 'ADMIN');

INSERT INTO usuario (username, email, password_hash, rol) 
VALUES ('estudio_dev', 'empresa@bda.com', 'empresa123', 'EMPRESA');

INSERT INTO usuario (username, email, password_hash, rol) 
VALUES ('gamer_pro', 'gamer@bda.com', 'gamer123', 'USUARIO');

-- Insertar géneros base
INSERT INTO genero (nombre) VALUES ('Acción');
INSERT INTO genero (nombre) VALUES ('Aventura');
INSERT INTO genero (nombre) VALUES ('RPG');
INSERT INTO genero (nombre) VALUES ('Deportes');
INSERT INTO genero (nombre) VALUES ('Terror');
INSERT INTO genero (nombre) VALUES ('Estrategia');
INSERT INTO genero (nombre) VALUES ('Simulación');

COMMIT;
